# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Console
email: jaeheelee0113@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
production_url: "http://localhost:3000"
url: http://localhost:3000 # the base hostname & protocol for your site, e.g. http://example.com
permalink: /posts/:categories/:title

# Footer social links if not provided then the icon would not be visible
twitter_username: jaehee0113
github_username:  jaehee0113
youtube_username: jaehee0113
linkedin_username: jaehee0113

# Disqus settings (shortname is sufficient)
disqus_shortname: Philsensus

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-polyglot

# Jekyll paginate settings
paginate: 10
paginate_path: "/archive/page:num/"

# sass settings (you can turn this on but please run gulp)
#sass:
#  sass_dir: _sass
#  style: compressed

# Jekyll polyglot settings
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false
